<?php

    return
    (
        array
        (
            1 => array (
                " CREATE TABLE IF NOT EXISTS FILES (SHA1_HASH CHAR(40) PRIMARY KEY, PATH VARCHAR(4096) NOT NULL, NAME VARCHAR(255) NOT NULL, ATIME INTEGER NOT NULL, MTIME INTEGER NOT NULL); ",
            ),
            2 => array(
                " CREATE TABLE IF NOT EXISTS FILE_ID3_TAG(SHA1_HASH CHAR(40) PRIMARY KEY, TITLE VARCHAR(128), ARTIST VARCHAR(128), ALBUM_ARTIST VARCHAR(128), ALBUM VARCHAR(128), YEAR CHAR(4), MB_ARTIST_ID CHAR(36), MB_ALBUM_ID CHAR(36)); "
            )
        )
    );

?>